let arrays = {
    behavioral_cue: [
        "Take a 10-minute walk outside",
        "Text someone you haven't talked to in a while",
        "Drink a full glass of water right now",
        "Write down 3 things you're grateful for",
        "Do 20 pushups or stretches",
        "Put your phone in another room for an hour",
        "Read 10 pages of a book",
        "Call a family member or friend",
        "Organize one small space in your home",
        "Learn one new word in another language",
        "Cook a meal instead of ordering out",
        "Spend 5 minutes in silence or meditation",
        "Compliment someone genuinely",
        "Try a new route on your commute",
        "Listen to a podcast episode",
        "Delete 10 old photos from your phone",
        "Do something creative for 15 minutes",
        "Make your bed right after waking up",
        "Say no to one thing that drains you",
        "Sit with good posture for the next hour",
        "Journal for 5 minutes",
        "Try one new food or recipe",
        "Unsubscribe from 3 emails you don't read",
        "Do a random act of kindness",
        "Take 10 deep breaths",
        "Start that thing you've been putting off",
        "Go to bed 30 minutes earlier tonight",
        "Listen to your favorite song and really focus",
        "Clean out your wallet or bag",
        "Smile at a stranger",
        "Set one goal for tomorrow",
        "Turn off notifications for 2 hours",
        "Try a new coffee shop or cafe",
        "Write a thank you note to someone",
        "Do a 5-minute desk cleanup",
        "Take the stairs instead of the elevator next time",
        "Listen to an album all the way through",
        "Watch a TED talk",
        "Sketch or doodle for 10 minutes",
        "Go for a bike ride",
        "Read an article about something new",
        "Do a digital detox for the evening",
        "Listen to a song for your current mood",
        "Try a new walking route in your neighborhood",
        "Spend 15 minutes planning your week",
        "Watch the sunset or sunrise",
        "Practe a skill you want to improve for 15 minutes",
        "Rearrange your workspace",
        "Take a cold shower",
        "Ask someone about their day and really listen"
    ],
    phrase: [
        'img/mgi-1.jpg',
        'img/mgi-2.jpg',
        'img/mgi-3.jpg',
        'img/mgi-4.jpg',
        'img/mgi-5.jpg',
        'img/mgi-6.jpg',
        'img/mgi-7.jpg',
        'img/mgi-8.jpg',
        'img/mgi-9.jpg',
        'img/mgi-10.jpg',
        'img/mgi-11.jpg',
        'img/mgi-12.jpg',
        'img/mgi-13.jpg',
        'img/mgi-14.jpg',
        'img/mgi-15.jpg',
        'img/mgi-16.jpg',
        'img/mgi-17.jpg',
        'img/mgi-18.jpg',
        'img/mgi-19.jpg',
        'img/mgi-20.jpg',
        'img/mgi-21.jpg',
        'img/mgi-22.jpg',
        'img/mgi-23.jpg',
        'img/mgi-24.jpg',
        'img/mgi-25.jpg',
        'img/mgi-26.jpg',
        'img/mgi-27.jpg',
        'img/mgi-28.jpg',
        'img/mgi-29.jpg',
        'img/mgi-30.jpg',
        'img/mgi-31.jpg',
        'img/mgi-32.jpg',
        'img/mgi-33.jpg',
        'img/mgi-34.jpg',
        'img/mgi-35.jpg',
        'img/mgi-36.jpg',
        'img/mgi-37.jpg',
        'img/mgi-38.jpg',
        'img/mgi-39.jpg',
        'img/mgi-40.jpg',
        'img/mgi-41.jpg',
        'img/mgi-42.jpg',
        'img/mgi-43.jpg',
        'img/mgi-44.jpg',
        'img/mgi-45.jpg',
        'img/mgi-46.jpg',
        'img/mgi-47.jpg',
        'img/mgi-48.jpg',
        'img/mgi-49.jpg',
        'img/mgi-50.jpg'
    ],
    coffee: [
        "Americano",
        "Espresso",
        "Macchiato",
        "Long Black",
        "Capuccino",
        "V60",
        "Chemex",
        "Origami",
        "Chai Latte",
        "Chai Tea",
        "Flat White",
        "Matcha Latte",
        "Matcha Tea",
        "Hot Chocolate",
        "French Press",
        "Latte",
        "Dirty Chai",
        "Cold Brew Tonic",
        "Ginger Cold Brew",
        "Steam Cold Brew",
        "Frappe Cafe",
        "Chai Frappe",
        "A bottle of water",
        "Espresso Martini",
        "Cortado",
        "Affogato",
        "Mocha",
        "Iced Latte",
        "Iced Americano",
        "Nitro Cold Brew",
        "Caramel Macchiato",
        "Vanilla Latte",
        "Oat Milk Latte",
        "Lavender Latte",
        "Spanish Latte",
        "Piccolo",
        "Ristretto",
        "Aeropress",
        "Turkish Coffee",
        "Vietnamese Coffee",
        "Irish Coffee",
        "White Chocolate Mocha",
        "Iced Matcha",
        "London Fog",
        "Earl Grey Latte",
        "Turmeric Latte",
        "Beetroot Latte",
        "Honey Cinnamon Latte",
        "Iced Chai",
        "Sparkling Water"
    ]
};

let randomNum = (Math.floor(Math.random()*50));

let behavior = () => {
    console.log(arrays.behavioral_cue[randomNum])
}
let phrase = () => {
    console.log(arrays.phrase[randomNum])
}
let coffee = () => {
    console.log(arrays.coffee[randomNum])
}

behavior();
phrase();
coffee();